# Generated by Django 2.0.2 on 2018-09-12 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('pub_date', models.DateTimeField()),
                ('image', models.ImageField(upload_to='images/blog/')),
                ('icon', models.ImageField(upload_to='images/blog/')),
                ('body', models.TextField()),
                ('url', models.TextField()),
                ('vote_total', models.IntegerField(default=1)),
                ('incubator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
