# Generated by Django 2.0.2 on 2018-09-12 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='vote_total',
            new_name='votes_total',
        ),
    ]
